baseURL = "https://test.collegiumacademicum.de"
title = "Collegium Academicum"
DefaultContentLanguage = "de"
Paginate = 5
assetDir = '.'
relativeURLs = true


[params]
sml_imgsize = "600"
med_imgsize = "900"
big_imgsize = "1800"

  [params.zimmermodell]
  longitude = 8.68685
  latitude = 49.37632
  location = ""

  [params.heidelberg]
  longitude = 8.6871
  latitude = 49.4013

  [params.hospital]
  longitude = 8.686231829139132
  latitude = 49.37589920283469

[languages]
  [languages.de]
  languageName = 'Deutsch'
  weight = 1

  [languages.en]
  languageName = 'English'
  weight = 2

  [languages.fr]
  languageName = 'Français'
  disabled = true
  weight = 3

  [languages.ru]
  languageName = 'Русский'
  disabled = true
  weight = 4

[imaging]
quality = 60
resampleFilter = "lanczos"

[permalinks]
pages = "/:slug/"
post = "/:year/:month/:day/:title/"
audio ="/:slug/"

[mediaTypes]
  [mediaTypes."audio/mpeg3"]
  suffixes = ["mp3"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
