[[main]]
    name = "Über uns"
    url = "/ueber-uns"
    weight = 1
[[main]]
    name = "Aktuelles"
    url = "/aktuelles"
    weight = 1
    parent = "Über uns"
[[main]]
    name = "Projektvorstellung und Timeline"
    url = "/projektvorstellung"
    weight = 2
    parent = "Über uns"
[[main]]
    name = "Unser Leitbild"
    url = "/leitbild"
    weight = 3
    parent = "Über uns"
[[main]]
    name = "Geschichte des alten CA"
    url = "/geschichte"
    weight = 4
    parent = "Über uns"
[[main]]
    name = "In der Presse"
    url = "/presse"
    weight = 5
    parent = "Über uns"
[[main]]
    name = "Literatur und eigene Veröffentlichungen"
    url = "/literatur"
    weight = 6
    parent = "Über uns"

[[main]]
    name = "Wohnen"
    url = "/wohnen"
    weight = 3
[[main]]
    name = "Wohnheim"
    url = "/wohnheim"
    weight = 1
    parent = "Wohnen"
[[main]]
    name = "Sozialer Mietwohnraum"
    url = "/mietwohnraum"
    weight = 2
    parent = "Wohnen"
[[main]]
    name = "Selbstverwaltung"
    url = "/selbstverwaltung"
    weight = 3
    parent = "Wohnen"
[[main]]
    name = "Barrierefreiheit"
    url = "/barrierefreiheit"
    weight = 4
    parent = "Wohnen"
[[main]]
    name = "FAQ"
    url = "/faq"
    weight = 5
    parent = "Wohnen"

[[main]]
    name = "Orientierungsjahr"
    url = "/orientierungsjahr"
    weight = 4

[[main]]
    name = "Veranstaltungen"
    url = "/veranstaltungen"
    weight = 5
[[main]]
    name = "Aktionen"
    url = "/aktionen"
    weight = 1
    parent = "Veranstaltungen"
[[main]]
    name = "Veranstaltungekalender"
    url = "/kalender"
    weight = 2
    parent = "Veranstaltungen"
[[main]]
    name = "Räume nutzen und mieten"
    url = "/raum"
    weight = 3
    parent = "Veranstaltungen"
[[main]]
    name = "Anfahrt"
    url = "/anfahrt"
    weight = 3
    parent = "Veranstaltungen"
[[main]]
    name = "Café"
    url = "/cafe"
    weight = 3
    parent = "Veranstaltungen"

[[main]]
    name = "Unterstützen"
    url = "/unterstuetzen"
    weight = 6
[[main]]
    name = "Finanzierung"
    url = "/finanzierung"
    weight = 1
    parent = "Unterstützen"
[[main]]
    name = "Direktkredite"
    url = "/direktkredite"
    weight = 2
    parent = "Unterstützen"
[[main]]
    name = "Spenden"
    url = "/spenden"
    weight = 3
    parent = "Unterstützen"
[[main]]
    name = "Förderverein"
    url = "/foerderverein"
    weight = 4
    parent = "Unterstützen"
