[[main]]
    name = "Housing Project"
    url = "/housing-project"
    weight = 1
[[main]]
    name = "Our buildings"
    url = "/buildings"
    weight = 1
    parent = "Housing Project"
[[main]]
    name = "Education"
    url = "/education"
    weight = 2
    parent = "Housing Project"
[[main]]
    name = "Sustainability"
    url = "/sustainability"
    weight = 3
    parent = "Housing Project"
[[main]]
    name = "Self-management"
    url = "/self-management"
    weight = 4
    parent = "Housing Project"
[[main]]
    name = "Funding"
    url = "/funding"
    weight = 5
    parent = "Housing Project"

[[main]]
    name = "Support"
    url = "/support"
    weight = 2
[[main]]
    name = "Join us!"
    url = "/join-us"
    weight = 1
    parent = "Support"
[[main]]
    name = "Direct loans"
    url = "/direct-loans"
    weight = 2
    parent = "Support"
[[main]]
    name = "Donations"
    url = "/donations"
    weight = 3
    parent = "Support"
[[main]]
    name = "Activities"
    url = "/activities"
    weight = 4
    parent = "Support"
[[main]]
    name = "About us"
    url = "/about-us"
    weight = 3
[[main]]
    name = "Our vision"
    url = "/vision"
    weight = 1
    parent = "About us"
[[main]]
    name = "Links & Press"
    url = "/press-links"
    weight = 2
    parent = "About us"
[[main]]
    name = "Timeline"
    url = "/timeline"
    weight = 3
    parent = "About us"
[[main]]
    name = "Partners"
    url = "/partners"
    weight = 4
    parent = "About us"
[[main]]
    name = "How to get to us"
    url = "/map"
    weight = 5
    parent = "About us"

[[main]]
    name = "Living"
    url = "/living"
    weight = 5
[[main]]
    name = "Dorm"
    url = "/dorm"
    weight = 1
    parent = "Living"
[[main]]
    name = "Social rental housing"
    url = "/rental-housing"
    weight = 2
    parent = "Living"
[[main]]
    name = "Freely financed apartments"
    url = "/freely_financed_apartments"
    weight = 3
    parent = "Living"
[[main]]
    name = "Freely financed apartments"
    url = "/freely_financed_apartments"
    weight = 4
    parent = "Living"
[[main]]
    name = "Temporary rooms"
    url = "/temporary_rooms"
    weight = 5
    parent = "Living"
[[main]]
    name = "FAQ"
    url = "/faq"
    weight = 6
    parent = "Living"
[[main]]
    name = "Accessibility"
    url = "/accessibility"
    weight = 7
    parent = "Living"
