[[main]]
    pre = '<i class="icon-home"></i>'
    url = "/"
    weight = 1

[[main]]
    name = "Aktuelles"
    url = "/aktuelles"
    weight = 2

[[main]]
    name = "Hausprojekt"
    url = "/hausprojekt"
    weight = 3
[[main]]
    name = "Unsere Gebäude"
    url = "/gebaeude"
    weight = 1
    parent = "Hausprojekt"
[[main]]
    name = "Bildung"
    url = "/bildung"
    weight = 2
    parent = "Hausprojekt"
[[main]]
    name = "Nachhaltigkeit"
    url = "/nachhaltigkeit"
    weight = 3
    parent = "Hausprojekt"
[[main]]
    name = "Selbstverwaltung"
    url = "/selbstverwaltung"
    weight = 4
    parent = "Hausprojekt"

[[main]]
    name = "Über uns"
    url = "/ueber-uns"
    weight = 4
[[main]]
    name = "Unser Leitbild"
    url = "/leitbild"
    weight = 1
    parent = "Über uns"
[[main]]
    name = "Geschichte des alten CA"
    url = "/geschichte"
    weight = 2
    parent = "Über uns"
[[main]]
    name = "Timeline"
    url = "/timeline"
    weight = 3
    parent = "Über uns"
[[main]]
    name = "In der Presse"
    url = "/presse"
    weight = 4
    parent = "Über uns"
[[main]]
    name = "Literatur und eigene Veröffentlichungen"
    url = "/literatur"
    weight = 5
    parent = "Über uns"

[[main]]
    name = "Orientierungsjahr faltr"
    url = "/orientierungsjahr"
    weight = 5

[[main]]
    name = "Unterstützen"
    url = "/unterstuetzen"
    weight = 6
[[main]]
    name = "Finanzierung"
    url = "/finanzierung"
    weight = 1
    parent = "Unterstützen"
[[main]]
    name = "Direktkredite"
    url = "/direktkredite"
    weight = 2
    parent = "Unterstützen"
[[main]]
    name = "Spenden"
    url = "/spenden"
    weight = 3
    parent = "Unterstützen"
[[main]]
    name = "Mach mit"
    url = "/mach-mit"
    weight = 4
    parent = "Unterstützen"
[[main]]
    name = "Förderverein"
    url = "/foerderverein"
    weight = 5
    parent = "Unterstützen"

[[main]]
    name = "Wohnen"
    url = "/wohnen"
    weight = 7
[[main]]
    name = "Wohnheim"
    url = "/wohnheim"
    weight = 1
    parent = "Wohnen"
[[main]]
    name = "Sozialer Mietwohnraum"
    url = "/sozialer_mietwohnraum"
    weight = 2
    parent = "Wohnen"
[[main]]
    name = "Ungeförderte Wohnungen"
    url = "/freifinanzierte_wohnungen"
    weight = 3
    parent = "Wohnen"
[[main]]
    name = "Befristete Zimmer"
    url = "/befristete_zimmer"
    weight = 4
    parent = "Wohnen"
[[main]]
    name = "FAQ"
    url = "/faq"
    weight = 6
    parent = "Wohnen"
[[main]]
    name = "Barrierefreiheit"
    url = "/barrierefreiheit"
    weight = 7
    parent = "Wohnen"

[[main]]
    name = "Kontakt"
    url = "/anfahrt"
    weight = 8
