[[main]]
    name = "ПРОЕКТ ЖИЛОГО КОМПЛЕКСА"
    url = "/ПРОЕКТ-ЖИЛОГО-КОМПЛЕКСА"
    weight = 1
[[main]]
    name = "ЖИЛЬЕ"
    url = "/ЖИЛЬЕ"
    weight = 1
    parent = "ПРОЕКТ ЖИЛОГО КОМПЛЕКСА"
[[main]]
    name = "ОБРАЗОВАНИЕ"
    url = "/ОБРАЗОВАНИЕ"
    weight = 2
    parent = "ПРОЕКТ ЖИЛОГО КОМПЛЕКСА"
[[main]]
    name = "ЭКОЛОГИЧНОСТЬ"
    url = "/ЭКОЛОГИЧНОСТЬ"
    weight = 3
    parent = "ПРОЕКТ ЖИЛОГО КОМПЛЕКСА"
[[main]]
    name = "САМОУПРАВЛЕНИЕ"
    url = "/САМОУПРАВЛЕНИЕ"
    weight = 4
    parent = "ПРОЕКТ ЖИЛОГО КОМПЛЕКСА"
[[main]]
    name = "ФИНАНСИРОВАНИЕ"
    url = "/ФИНАНСИРОВАНИЕ"
    weight = 5
    parent = "ПРОЕКТ ЖИЛОГО КОМПЛЕКСА"

[[main]]
    name = "ПОДДЕРЖАТЬ"
    url = "/ПОДДЕРЖАТЬ"
    weight = 2
[[main]]
    name = "ПРИСОЕДИНЯЙСЯ!"
    url = "/ПРИСОЕДИНЯЙСЯ"
    weight = 1
    parent = "ПОДДЕРЖАТЬ"
[[main]]
    name = "ПРЯМЫЕ КРЕДИТЫ"
    url = "/ПРЯМЫЕ-КРЕДИТЫ"
    weight = 2
    parent = "ПОДДЕРЖАТЬ"
[[main]]
    name = "ПОЖЕРТВОВАНИЯ"
    url = "/ПОЖЕРТВОВАНИЯ"
    weight = 3
    parent = "ПОДДЕРЖАТЬ"

[[main]]
    name = "О НАС"
    url = "/О-НАС"
    weight = 3
[[main]]
    name = "НАША ФИЛОСОФИЯ"
    url = "/ФИЛОСОФИЯ"
    weight = 1
    parent = "О НАС"
[[main]]
    name = "Ссылки и пресса"
    url = "/пресса"
    weight = 2
    parent = "О НАС"
[[main]]
    name = "Партнеры"
    url = "/Партнеры"
    weight = 3
    parent = "О НАС"
