baseURL = "https://collegiumacademicum.de"
title = "Collegium Academicum"
DefaultContentLanguage = "de"
Paginate = 5

[params]
sml_imgsize = "600"
med_imgsize = "900"
big_imgsize = "1800"

[languages]
[languages.de]
languageName = 'Deutsch'
weight = 1

[languages.en]
languageName = 'English'
weight = 2

[imaging]
quality = 60
resampleFilter = "lanczos"

[permalinks]
pages = "/:slug/"
post = "/:year/:month/:day/:title/"
audio ="/:slug/"

[mediaTypes]
  [mediaTypes."audio/mpeg3"]
  suffixes = ["mp3"]
