baseURL = "https://collegiumacademicum.de"
title = "Collegium Academicum"
DefaultContentLanguage = "de"

[languages]
[languages.de]
languageName = 'Deutsch'
weight = 1

[languages.en]
languageName = 'English'
weight = 2

[imaging]
quality = 75

[permalinks]
pages = "/:slug/"
post = "/:year/:month/:day/:title/"
