name: Build with Hugo and Juice and deploy to FTP server

on:
  push:
    branches: ["master"]

  workflow_dispatch:

concurrency:
  group: "ftp"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.123.8
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install ncftp
        run: sudo apt install ncftp
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js dependencies
        run: "npm ci"
      - name: Build with Hugo and Juice
        run: bash build.sh
      - name: Upload to FTP
        run: ncftpput -R -v -u ${{ secrets.FTP_USER }} -p ${{ secrets.FTP_PASSWORD }} -P ${{ secrets.FTP_PORT }} ${{ secrets.FTP_HOST }} /web/website_github_test/ /upload